apiVersion: apps/v1
kind: Deployment
metadata:
    name: raghav-web-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: raghav-web-app
    template:
        metadata:
            labels:
                app: raghav-web-app
        spec:
            containers:
                - name: raghav-web-app
                  image: raghavcodes/raghav-web-app:latest
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "500m"
                          memory: "256Mi"
