apiVersion: v1
kind: Service
metadata:
    name: raghav-web-app-service
spec:
    selector:
        app: raghav-web-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: LoadBalancer
